const FETCH_API_KEY = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2NTAyODFkZjYwMzU0ZjUzZTNhNzIwNmU1NDM5MTg3MiIsIm5iZiI6MTc0MDExMjA1My40Mywic3ViIjoiNjdiODAwYjU0NDRkZDdmY2VmYmE0NzZmIiwic2NvcGVzIjpbImFwaV9yZWFkIl0sInZlcnNpb24iOjF9.A00TRpe579X3liSSOW_P1DQmOCecqWuK3iuk_kKJ3c4'
const FETCH_BASE_URL = 'https://api.themoviedb.org/3/movie/'

export default { FETCH_API_KEY, FETCH_BASE_URL }